"""Shared constants used across GEE processing scripts."""

# Output resolution and projection for all final map products
scale = 30
crs = 'EPSG:3571'

# Coordinate list for the pan-Arctic export bounding box.
# Stored as a plain list (not ee.Geometry) so this module can be imported
# before ee.Initialize() is called. Construct the geometry inline:
#   ee.Geometry.Polygon(params.export_region_coords, None, False)
export_region_coords = [-180, 88, 0, 88, 180, 88, 180, 45, 0, 45, -180, 45]

# Canopy height threshold (m) used to define tree/shrub presence in the hurdle model
canopy_height_threshold = 5

# GEE project ID
ee_project = 'arctic-biomass-mapping'
ee_project_production = 'geode-gee' # Only for productions scripts that have been thoroughly vetted using ee_project

_ECOREGION_SHORT = {
    'ecoregion_AhklunandKilbuckUplandTundra': 'er_001',
    'ecoregion_AlashanPlateausemidesert': 'er_002',
    'ecoregion_AlaskaPeninsulamontanetaiga': 'er_003',
    'ecoregion_AlaskaStEliasRangetundra': 'er_004',
    'ecoregion_AlbertaBritishColumbiafoothillsforests': 'er_005',
    'ecoregion_AleutianIslandstundra': 'er_006',
    'ecoregion_Alpsconiferandmixedforests': 'er_007',
    'ecoregion_Altaialpinemeadowandtundra': 'er_008',
    'ecoregion_Altaimontaneforestandforeststeppe': 'er_009',
    'ecoregion_Altaisteppeandsemidesert': 'er_010',
    'ecoregion_Amurmeadowsteppe': 'er_011',
    'ecoregion_Arcticcoastaltundra': 'er_012',
    'ecoregion_Arcticfoothillstundra': 'er_013',
    'ecoregion_Balkanmixedforests': 'er_014',
    'ecoregion_Balticmixedforests': 'er_015',
    'ecoregion_Beringialowlandtundra': 'er_016',
    'ecoregion_Beringiauplandtundra': 'er_017',
    'ecoregion_BlueMountainsforests': 'er_018',
    'ecoregion_BritishColumbiacoastalconiferforests': 'er_019',
    'ecoregion_BrooksBritishRangetundra': 'er_020',
    'ecoregion_Caledonconiferforests': 'er_021',
    'ecoregion_CanadianAspenforestsandparklands': 'er_022',
    'ecoregion_CanadianHighArctictundra': 'er_023',
    'ecoregion_CanadianLowArctictundra': 'er_024',
    'ecoregion_CanadianMiddleArcticTundra': 'er_025',
    'ecoregion_Cantabrianmixedforests': 'er_026',
    'ecoregion_Carpathianmontaneforests': 'er_027',
    'ecoregion_Caspianlowlanddesert': 'er_028',
    'ecoregion_Celticbroadleafforests': 'er_029',
    'ecoregion_CentralAsiannortherndesert': 'er_030',
    'ecoregion_CentralAsianriparianwoodlands': 'er_031',
    'ecoregion_CentralBritishColumbiaMountainforests': 'er_032',
    'ecoregion_CentralCanadianShieldforests': 'er_033',
    'ecoregion_CentralEuropeanmixedforests': 'er_034',
    'ecoregion_CentralPacificNorthwestcoastalforests': 'er_035',
    'ecoregion_CentralSouthernCascadesForests': 'er_036',
    'ecoregion_CentralTallgrassprairie': 'er_037',
    'ecoregion_ChangbaiMountainsmixedforests': 'er_038',
    'ecoregion_CherskiiKolymamountaintundra': 'er_039',
    'ecoregion_ChukchiPeninsulatundra': 'er_040',
    'ecoregion_CookInlettaiga': 'er_041',
    'ecoregion_CopperPlateautaiga': 'er_042',
    'ecoregion_CrimeanSubmediterraneanforestcomplex': 'er_043',
    'ecoregion_DaHingganDzhagdyMountainsconiferforests': 'er_044',
    'ecoregion_Daurianforeststeppe': 'er_045',
    'ecoregion_DavisHighlandstundra': 'er_046',
    'ecoregion_DinaricMountainsmixedforests': 'er_047',
    'ecoregion_EastEuropeanforeststeppe': 'er_048',
    'ecoregion_EastSiberiantaiga': 'er_049',
    'ecoregion_EasternCanadianForestBorealtransition': 'er_050',
    'ecoregion_EasternCanadianShieldtaiga': 'er_051',
    'ecoregion_EasternCanadianforests': 'er_052',
    'ecoregion_EasternCascadesforests': 'er_053',
    'ecoregion_EasternGobidesertsteppe': 'er_054',
    'ecoregion_EasternGreatLakeslowlandforests': 'er_055',
    'ecoregion_EminValleysteppe': 'er_056',
    'ecoregion_EnglishLowlandsbeechforests': 'er_057',
    'ecoregion_EuropeanAtlanticmixedforests': 'er_058',
    'ecoregion_FaroeIslandsborealgrasslands': 'er_059',
    'ecoregion_FraserPlateauandBasinconiferforests': 'er_060',
    'ecoregion_GobiLakesValleydesertsteppe': 'er_061',
    'ecoregion_GreatLakesBasindesertsteppe': 'er_062',
    'ecoregion_GulfofStLawrencelowlandforests': 'er_063',
    'ecoregion_Hokkaidodeciduousforests': 'er_064',
    'ecoregion_Hokkaidomontaneconiferforests': 'er_065',
    'ecoregion_Icelandborealbirchforestsandalpinetundra': 'er_066',
    'ecoregion_Illyriandeciduousforests': 'er_067',
    'ecoregion_InteriorAlaskaYukonlowlandtaiga': 'er_068',
    'ecoregion_InteriorYukonAlaskaalpinetundra': 'er_069',
    'ecoregion_Italiansclerophyllousandsemideciduousforests': 'er_070',
    'ecoregion_JunggarBasinsemidesert': 'er_071',
    'ecoregion_KalaallitNunaatArcticsteppe': 'er_072',
    'ecoregion_KalaallitNunaatHighArctictundra': 'er_073',
    'ecoregion_KamchatkaKurilemeadowsandsparseforests': 'er_074',
    'ecoregion_Kamchatkataiga': 'er_075',
    'ecoregion_Kamchatkatundra': 'er_076',
    'ecoregion_Kazakhforeststeppe': 'er_077',
    'ecoregion_Kazakhsemidesert': 'er_078',
    'ecoregion_Kazakhsteppe': 'er_079',
    'ecoregion_Kazakhuplandsteppe': 'er_080',
    'ecoregion_KhangaiMountainsalpinemeadow': 'er_081',
    'ecoregion_KhangaiMountainsconiferforests': 'er_082',
    'ecoregion_KolaPeninsulatundra': 'er_083',
    'ecoregion_Manchurianmixedforests': 'er_084',
    'ecoregion_MidCanadaBorealPlainsforests': 'er_085',
    'ecoregion_MidwestCanadianShieldforests': 'er_086',
    'ecoregion_MongolianManchuriangrassland': 'er_087',
    'ecoregion_MontanaValleyandFoothillgrasslands': 'er_088',
    'ecoregion_MuskwaSlaveLaketaiga': 'er_089',
    'ecoregion_NenjiangRivergrassland': 'er_090',
    'ecoregion_NewEnglandAcadianforests': 'er_091',
    'ecoregion_NorthAtlanticmoistmixedforests': 'er_092',
    'ecoregion_NorthCascadesconiferforests': 'er_093',
    'ecoregion_NortheastChinaPlaindeciduousforests': 'er_094',
    'ecoregion_NortheastSiberiancoastaltundra': 'er_095',
    'ecoregion_NortheastSiberiantaiga': 'er_096',
    'ecoregion_NortheastSpainandSouthernFranceMediterraneanforests': 'er_097',
    'ecoregion_NorthernCanadianShieldtaiga': 'er_098',
    'ecoregion_NorthernCordilleraforests': 'er_099',
    'ecoregion_NorthernPacificAlaskancoastalforests': 'er_100',
    'ecoregion_NorthernRockiesconiferforests': 'er_101',
    'ecoregion_NorthernShortgrassprairie': 'er_102',
    'ecoregion_NorthernTallgrassprairie': 'er_103',
    'ecoregion_NorthwestRussianNovayaZemlyatundra': 'er_104',
    'ecoregion_NorthwestTerritoriestaiga': 'er_105',
    'ecoregion_NovosibirskIslandsArcticdesert': 'er_106',
    'ecoregion_OgilvieMacKenziealpinetundra': 'er_107',
    'ecoregion_Okanogandryforests': 'er_108',
    'ecoregion_OkhotskManchuriantaiga': 'er_109',
    'ecoregion_PacificCoastalMountainicefieldsandtundra': 'er_110',
    'ecoregion_Palouseprairie': 'er_111',
    'ecoregion_Pannonianmixedforests': 'er_112',
    'ecoregion_PoBasinmixedforests': 'er_113',
    'ecoregion_Ponticsteppe': 'er_114',
    'ecoregion_Pugetlowlandforests': 'er_115',
    'ecoregion_QueenCharlotteIslandsconiferforests': 'er_116',
    'ecoregion_RockandIce': 'er_117',
    'ecoregion_RussianArcticdesert': 'er_118',
    'ecoregion_RussianBeringtundra': 'er_119',
    'ecoregion_SakhalinIslandtaiga': 'er_120',
    'ecoregion_Sarmaticmixedforests': 'er_121',
    'ecoregion_SayanIntermontanesteppe': 'er_122',
    'ecoregion_Sayanalpinemeadowsandtundra': 'er_123',
    'ecoregion_Sayanmontaneconiferforests': 'er_124',
    'ecoregion_ScandinavianMontaneBirchforestandgrasslands': 'er_125',
    'ecoregion_ScandinavianandRussiantaiga': 'er_126',
    'ecoregion_Scandinaviancoastalconiferforests': 'er_127',
    'ecoregion_SelengeOrkhonforeststeppe': 'er_128',
    'ecoregion_SouthCentralRockiesforests': 'er_129',
    'ecoregion_SouthSiberianforeststeppe': 'er_130',
    'ecoregion_SouthernHudsonBaytaiga': 'er_131',
    'ecoregion_SuiphunKhankameadowsandforestmeadows': 'er_132',
    'ecoregion_TaimyrCentralSiberiantundra': 'er_133',
    'ecoregion_TianShanfoothillaridsteppe': 'er_134',
    'ecoregion_TianShanmontanesteppeandmeadows': 'er_135',
    'ecoregion_TorngatMountaintundra': 'er_136',
    'ecoregion_TransBaikalBaldMountaintundra': 'er_137',
    'ecoregion_TransBaikalconiferforests': 'er_138',
    'ecoregion_TyrrhenianAdriaticsclerophyllousandmixedforests': 'er_139',
    'ecoregion_UpperMidwestUSforestsavannatransition': 'er_140',
    'ecoregion_Uralsmontaneforestandtaiga': 'er_141',
    'ecoregion_Ussuribroadleafandmixedforests': 'er_142',
    'ecoregion_WatsonHighlandstaiga': 'er_143',
    'ecoregion_WestSiberiantaiga': 'er_144',
    'ecoregion_WesternEuropeanbroadleafforests': 'er_145',
    'ecoregion_WesternGreatLakesforests': 'er_146',
    'ecoregion_WesternSiberianhemiborealforests': 'er_147',
    'ecoregion_WillametteValleyoaksavanna': 'er_148',
    'ecoregion_WrangelIslandArcticdesert': 'er_149',
    'ecoregion_WyomingBasinshrubsteppe': 'er_150',
    'ecoregion_YamalGydantundra': 'er_151',
    'ecoregion_other': 'er_152',
}
